name: rna_seq_qpn
dependencies:
        - python=3.8
        - mamba
        - FastQC
        - cutadapt 
        - star
        - samtools
        - htseq
        - r-base
        - bioconductor-deseq2
        - salmon
        - picard
        - snakemake
        - sra-tools
